Finished another linting pass
  - ./tools/lint uses flake8 to catch basic structural errors (undefined names, etc...) and to preserve at least some basic consistent formatting
  - ./tools/typecheck uses mypy to catch inconsistent types, noting that it only works on parts of the code that have been type-annotated.

diff --git a/tools/lint b/tools/lint
--- a/tools/lint
+++ b/tools/lint
@@ -3,8 +3,9 @@
 DIR=$(dirname $0)/..
 cd $DIR
 
-if [ "$(which pyflakes)" ] ; then
-  flake8 --config=.flake8 vizier
+if [ "$(which flake8)" ] ; then
+  flake8 --config=.flake8 vizier || exit -1 
+  echo "No Errors"
 else
   echo "flake8 is not installed"
   echo
